# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'creepy.ui'
#
# Created: Tue Mar 26 00:03:15 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CreepyMainWindow(object):
    def setupUi(self, CreepyMainWindow):
        CreepyMainWindow.setObjectName(_fromUtf8("CreepyMainWindow"))
        CreepyMainWindow.resize(1483, 719)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CreepyMainWindow.sizePolicy().hasHeightForWidth())
        CreepyMainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../creepy/include/creepy.xpm")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CreepyMainWindow.setWindowIcon(icon)
        CreepyMainWindow.setAutoFillBackground(True)
        self.centralwidget = QtGui.QWidget(CreepyMainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.centralStackedWidget = QtGui.QStackedWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralStackedWidget.sizePolicy().hasHeightForWidth())
        self.centralStackedWidget.setSizePolicy(sizePolicy)
        self.centralStackedWidget.setAutoFillBackground(True)
        self.centralStackedWidget.setObjectName(_fromUtf8("centralStackedWidget"))
        self.mapPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapPage.sizePolicy().hasHeightForWidth())
        self.mapPage.setSizePolicy(sizePolicy)
        self.mapPage.setObjectName(_fromUtf8("mapPage"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.mapPage)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mapWebView = QtWebKit.QWebView(self.mapPage)
        self.mapWebView.setAutoFillBackground(True)
        self.mapWebView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.mapWebView.setObjectName(_fromUtf8("mapWebView"))
        self.horizontalLayout.addWidget(self.mapWebView)
        self.centralStackedWidget.addWidget(self.mapPage)
        self.analysisPage = QtGui.QWidget()
        self.analysisPage.setObjectName(_fromUtf8("analysisPage"))
        self.centralStackedWidget.addWidget(self.analysisPage)
        self.verticalLayout_2.addWidget(self.centralStackedWidget)
        CreepyMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(CreepyMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1483, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuCreepy = QtGui.QMenu(self.menubar)
        self.menuCreepy.setObjectName(_fromUtf8("menuCreepy"))
        self.menuNewProject = QtGui.QMenu(self.menuCreepy)
        self.menuNewProject.setObjectName(_fromUtf8("menuNewProject"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        CreepyMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(CreepyMainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        CreepyMainWindow.setStatusBar(self.statusbar)
        self.dockWLocationsList = QtGui.QDockWidget(CreepyMainWindow)
        self.dockWLocationsList.setMinimumSize(QtCore.QSize(250, 127))
        self.dockWLocationsList.setObjectName(_fromUtf8("dockWLocationsList"))
        self.dockWLocationsListContents = QtGui.QWidget()
        self.dockWLocationsListContents.setObjectName(_fromUtf8("dockWLocationsListContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWLocationsListContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.locationsTableView = QtGui.QTableView(self.dockWLocationsListContents)
        self.locationsTableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.locationsTableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.locationsTableView.setObjectName(_fromUtf8("locationsTableView"))
        self.verticalLayout.addWidget(self.locationsTableView)
        self.dockWLocationsList.setWidget(self.dockWLocationsListContents)
        CreepyMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWLocationsList)
        self.dockWProjects = QtGui.QDockWidget(CreepyMainWindow)
        self.dockWProjects.setMinimumSize(QtCore.QSize(200, 300))
        self.dockWProjects.setObjectName(_fromUtf8("dockWProjects"))
        self.dockWProjectsContents = QtGui.QWidget()
        self.dockWProjectsContents.setObjectName(_fromUtf8("dockWProjectsContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWProjectsContents)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.treeViewProjects = QtGui.QTreeView(self.dockWProjectsContents)
        self.treeViewProjects.setObjectName(_fromUtf8("treeViewProjects"))
        self.verticalLayout_3.addWidget(self.treeViewProjects)
        self.dockWProjects.setWidget(self.dockWProjectsContents)
        CreepyMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWProjects)
        self.dockWCurrentLocationDetails = QtGui.QDockWidget(CreepyMainWindow)
        self.dockWCurrentLocationDetails.setObjectName(_fromUtf8("dockWCurrentLocationDetails"))
        self.dockWCurrentTargetDetailsContents = QtGui.QWidget()
        self.dockWCurrentTargetDetailsContents.setObjectName(_fromUtf8("dockWCurrentTargetDetailsContents"))
        self.dockWCurrentLocationDetails.setWidget(self.dockWCurrentTargetDetailsContents)
        CreepyMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWCurrentLocationDetails)
        self.toolBar = QtGui.QToolBar(CreepyMainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        CreepyMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExport_as_kml = QtGui.QAction(CreepyMainWindow)
        self.actionExport_as_kml.setCheckable(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/cr/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport_as_kml.setIcon(icon1)
        self.actionExport_as_kml.setObjectName(_fromUtf8("actionExport_as_kml"))
        self.actionExport_as_csv = QtGui.QAction(CreepyMainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/cr/cvs.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport_as_csv.setIcon(icon2)
        self.actionExport_as_csv.setObjectName(_fromUtf8("actionExport_as_csv"))
        self.actionExit = QtGui.QAction(CreepyMainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionReport_a_problem_bug = QtGui.QAction(CreepyMainWindow)
        self.actionReport_a_problem_bug.setObjectName(_fromUtf8("actionReport_a_problem_bug"))
        self.actionAbout = QtGui.QAction(CreepyMainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionPluginsConfiguration = QtGui.QAction(CreepyMainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/cr/plugins_config.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPluginsConfiguration.setIcon(icon3)
        self.actionPluginsConfiguration.setObjectName(_fromUtf8("actionPluginsConfiguration"))
        self.actionLocations_List = QtGui.QAction(CreepyMainWindow)
        self.actionLocations_List.setCheckable(True)
        self.actionLocations_List.setChecked(True)
        self.actionLocations_List.setSoftKeyRole(QtGui.QAction.NoSoftKey)
        self.actionLocations_List.setObjectName(_fromUtf8("actionLocations_List"))
        self.actionResult_Details = QtGui.QAction(CreepyMainWindow)
        self.actionResult_Details.setCheckable(True)
        self.actionResult_Details.setChecked(True)
        self.actionResult_Details.setObjectName(_fromUtf8("actionResult_Details"))
        self.actionAvailable_Plugins = QtGui.QAction(CreepyMainWindow)
        self.actionAvailable_Plugins.setCheckable(True)
        self.actionAvailable_Plugins.setChecked(True)
        self.actionAvailable_Plugins.setObjectName(_fromUtf8("actionAvailable_Plugins"))
        self.actionCurrent_Target_Details = QtGui.QAction(CreepyMainWindow)
        self.actionCurrent_Target_Details.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolbarIcons/creepy32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCurrent_Target_Details.setIcon(icon4)
        self.actionCurrent_Target_Details.setObjectName(_fromUtf8("actionCurrent_Target_Details"))
        self.actionToolbars = QtGui.QAction(CreepyMainWindow)
        self.actionToolbars.setObjectName(_fromUtf8("actionToolbars"))
        self.actionSettings = QtGui.QAction(CreepyMainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionNewPersonProject = QtGui.QAction(CreepyMainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/cr/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewPersonProject.setIcon(icon5)
        self.actionNewPersonProject.setObjectName(_fromUtf8("actionNewPersonProject"))
        self.actionNewLocationBasedProject = QtGui.QAction(CreepyMainWindow)
        self.actionNewLocationBasedProject.setObjectName(_fromUtf8("actionNewLocationBasedProject"))
        self.actionGeolocateCurrentTarget = QtGui.QAction(CreepyMainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/cr/creepy32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGeolocateCurrentTarget.setIcon(icon6)
        self.actionGeolocateCurrentTarget.setObjectName(_fromUtf8("actionGeolocateCurrentTarget"))
        self.actionAnalyzeCurrentTarget = QtGui.QAction(CreepyMainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/cr/analyze.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAnalyzeCurrentTarget.setIcon(icon7)
        self.actionAnalyzeCurrentTarget.setObjectName(_fromUtf8("actionAnalyzeCurrentTarget"))
        self.menuNewProject.addAction(self.actionNewPersonProject)
        self.menuNewProject.addAction(self.actionNewLocationBasedProject)
        self.menuCreepy.addAction(self.menuNewProject.menuAction())
        self.menuCreepy.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionPluginsConfiguration)
        self.menuEdit.addAction(self.actionSettings)
        self.menuAbout.addAction(self.actionReport_a_problem_bug)
        self.menuAbout.addAction(self.actionAbout)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionToolbars)
        self.menubar.addAction(self.menuCreepy.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionNewPersonProject)
        self.toolBar.addAction(self.actionPluginsConfiguration)
        self.toolBar.addAction(self.actionExport_as_kml)
        self.toolBar.addAction(self.actionExport_as_csv)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionGeolocateCurrentTarget)
        self.toolBar.addAction(self.actionAnalyzeCurrentTarget)
        self.toolBar.addAction(self.actionCurrent_Target_Details)

        self.retranslateUi(CreepyMainWindow)
        self.centralStackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("activated()")), CreepyMainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(CreepyMainWindow)

    def retranslateUi(self, CreepyMainWindow):
        CreepyMainWindow.setWindowTitle(QtGui.QApplication.translate("CreepyMainWindow", "Greepy Geolocation Aggregator", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCreepy.setTitle(QtGui.QApplication.translate("CreepyMainWindow", "Creepy", None, QtGui.QApplication.UnicodeUTF8))
        self.menuNewProject.setTitle(QtGui.QApplication.translate("CreepyMainWindow", "New Project", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("CreepyMainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("CreepyMainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("CreepyMainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWLocationsList.setWindowTitle(QtGui.QApplication.translate("CreepyMainWindow", "Locations List", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWProjects.setWindowTitle(QtGui.QApplication.translate("CreepyMainWindow", "Target Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWCurrentLocationDetails.setWindowTitle(QtGui.QApplication.translate("CreepyMainWindow", "Current Location Details", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("CreepyMainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_as_kml.setText(QtGui.QApplication.translate("CreepyMainWindow", "Export as kml", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_as_csv.setText(QtGui.QApplication.translate("CreepyMainWindow", "Export as csv", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("CreepyMainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReport_a_problem_bug.setText(QtGui.QApplication.translate("CreepyMainWindow", "Report a problem / bug", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("CreepyMainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPluginsConfiguration.setText(QtGui.QApplication.translate("CreepyMainWindow", "Plugins Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLocations_List.setText(QtGui.QApplication.translate("CreepyMainWindow", "Locations List", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResult_Details.setText(QtGui.QApplication.translate("CreepyMainWindow", "Result Details", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAvailable_Plugins.setText(QtGui.QApplication.translate("CreepyMainWindow", "Available Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCurrent_Target_Details.setText(QtGui.QApplication.translate("CreepyMainWindow", "Current Target Details", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToolbars.setText(QtGui.QApplication.translate("CreepyMainWindow", "Toolbars", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("CreepyMainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewPersonProject.setText(QtGui.QApplication.translate("CreepyMainWindow", "Person Based Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewLocationBasedProject.setText(QtGui.QApplication.translate("CreepyMainWindow", "Location Based Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGeolocateCurrentTarget.setText(QtGui.QApplication.translate("CreepyMainWindow", "Geolocate Current Target", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGeolocateCurrentTarget.setToolTip(QtGui.QApplication.translate("CreepyMainWindow", "Geolocate Current Target", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAnalyzeCurrentTarget.setText(QtGui.QApplication.translate("CreepyMainWindow", "Analyze Current Target", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
import creepy_resources_rc
