# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'personProjectWizard.ui'
#
# Created: Thu Sep  6 19:05:30 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_newPersonProjectWizard(object):
    def setupUi(self, newPersonProjectWizard):
        newPersonProjectWizard.setObjectName(_fromUtf8("newPersonProjectWizard"))
        newPersonProjectWizard.resize(879, 658)
        self.newPersonBasedProjecWizardPage1 = QtGui.QWizardPage()
        self.newPersonBasedProjecWizardPage1.setSubTitle(_fromUtf8(""))
        self.newPersonBasedProjecWizardPage1.setObjectName(_fromUtf8("newPersonBasedProjecWizardPage1"))
        self.gridLayout = QtGui.QGridLayout(self.newPersonBasedProjecWizardPage1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.newPersonBasedProjecWizardPage1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 711, 82))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 2, 1, 2)
        self.lineEdit = QtGui.QLineEdit(self.newPersonBasedProjecWizardPage1)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.listView = QtGui.QListView(self.newPersonBasedProjecWizardPage1)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.gridLayout.addWidget(self.listView, 3, 2, 1, 2)
        self.label = QtGui.QLabel(self.newPersonBasedProjecWizardPage1)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_4 = QtGui.QLabel(self.newPersonBasedProjecWizardPage1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 5, 2, 1, 2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.newPersonBasedProjecWizardPage1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.line = QtGui.QFrame(self.newPersonBasedProjecWizardPage1)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 4, 2, 1, 2)
        self.label_3 = QtGui.QLabel(self.newPersonBasedProjecWizardPage1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.newPersonBasedProjecWizardPage1)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 2, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.listView_2 = QtGui.QListView(self.newPersonBasedProjecWizardPage1)
        self.listView_2.setObjectName(_fromUtf8("listView_2"))
        self.gridLayout.addWidget(self.listView_2, 6, 2, 1, 2)
        newPersonProjectWizard.addPage(self.newPersonBasedProjecWizardPage1)
        self.newPersonBasedProjecWizardPage2 = QtGui.QWizardPage()
        self.newPersonBasedProjecWizardPage2.setObjectName(_fromUtf8("newPersonBasedProjecWizardPage2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.newPersonBasedProjecWizardPage2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_8 = QtGui.QLabel(self.newPersonBasedProjecWizardPage2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 5, 4, 1, 1)
        self.calendarWidget_2 = QtGui.QCalendarWidget(self.newPersonBasedProjecWizardPage2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget_2.sizePolicy().hasHeightForWidth())
        self.calendarWidget_2.setSizePolicy(sizePolicy)
        self.calendarWidget_2.setObjectName(_fromUtf8("calendarWidget_2"))
        self.gridLayout_2.addWidget(self.calendarWidget_2, 2, 6, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.newPersonBasedProjecWizardPage2)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_2.addWidget(self.spinBox, 5, 1, 1, 1)
        self.commandLinkButton = QtGui.QCommandLinkButton(self.newPersonBasedProjecWizardPage2)
        self.commandLinkButton.setObjectName(_fromUtf8("commandLinkButton"))
        self.gridLayout_2.addWidget(self.commandLinkButton, 7, 6, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 2, 3, 1, 3)
        self.lineEdit_2 = QtGui.QLineEdit(self.newPersonBasedProjecWizardPage2)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_2.addWidget(self.lineEdit_2, 5, 6, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem3, 3, 6, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.newPersonBasedProjecWizardPage2)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_2.addWidget(self.checkBox_2, 4, 0, 1, 3)
        self.label_6 = QtGui.QLabel(self.newPersonBasedProjecWizardPage2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 6, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.newPersonBasedProjecWizardPage2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.calendarWidget = QtGui.QCalendarWidget(self.newPersonBasedProjecWizardPage2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        self.gridLayout_2.addWidget(self.calendarWidget, 2, 0, 1, 2)
        self.comboBox = QtGui.QComboBox(self.newPersonBasedProjecWizardPage2)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout_2.addWidget(self.comboBox, 5, 2, 1, 2)
        self.checkBox = QtGui.QCheckBox(self.newPersonBasedProjecWizardPage2)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_2.addWidget(self.checkBox, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem5, 3, 0, 1, 2)
        self.label_7 = QtGui.QLabel(self.newPersonBasedProjecWizardPage2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.newPersonBasedProjecWizardPage2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 6, 6, 1, 1)
        newPersonProjectWizard.addPage(self.newPersonBasedProjecWizardPage2)

        self.retranslateUi(newPersonProjectWizard)
        QtCore.QMetaObject.connectSlotsByName(newPersonProjectWizard)

    def retranslateUi(self, newPersonProjectWizard):
        newPersonProjectWizard.setWindowTitle(QtGui.QApplication.translate("newPersonProjectWizard", "New Person Project", None, QtGui.QApplication.UnicodeUTF8))
        self.newPersonBasedProjecWizardPage1.setTitle(QtGui.QApplication.translate("newPersonProjectWizard", "Set the target", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("newPersonProjectWizard", "Search for", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("newPersonProjectWizard", "Selected Targets", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("newPersonProjectWizard", "Available Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("newPersonProjectWizard", "Search Results ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("newPersonProjectWizard", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.newPersonBasedProjecWizardPage2.setTitle(QtGui.QApplication.translate("newPersonProjectWizard", "Configure the Search Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("newPersonProjectWizard", " from ", None, QtGui.QApplication.UnicodeUTF8))
        self.commandLinkButton.setText(QtGui.QApplication.translate("newPersonProjectWizard", "Select point from map", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setToolTip(QtGui.QApplication.translate("newPersonProjectWizard", "Use an address", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("newPersonProjectWizard", "Specify location boundaries for results : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("newPersonProjectWizard", "Until :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("newPersonProjectWizard", "From : ", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("newPersonProjectWizard", "Specify timeframe for results : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("newPersonProjectWizard", "Return results only within", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("newPersonProjectWizard", "or", None, QtGui.QApplication.UnicodeUTF8))

