# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'creepy.ui'
#
# Created: Wed Sep  5 00:07:18 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CreepyMainWindow(object):
    def setupUi(self, CreepyMainWindow):
        CreepyMainWindow.setObjectName(_fromUtf8("CreepyMainWindow"))
        CreepyMainWindow.resize(1483, 719)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CreepyMainWindow.sizePolicy().hasHeightForWidth())
        CreepyMainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../creepy/include/creepy.xpm")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CreepyMainWindow.setWindowIcon(icon)
        CreepyMainWindow.setAutoFillBackground(True)
        self.centralwidget = QtGui.QWidget(CreepyMainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.webView = QtWebKit.QWebView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webView.sizePolicy().hasHeightForWidth())
        self.webView.setSizePolicy(sizePolicy)
        self.webView.setMinimumSize(QtCore.QSize(800, 600))
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("file:///home/ioannis/code/creepy_dev/test.html")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.horizontalLayout.addWidget(self.webView)
        CreepyMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(CreepyMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1483, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuCreepy = QtGui.QMenu(self.menubar)
        self.menuCreepy.setObjectName(_fromUtf8("menuCreepy"))
        self.menuExport_as = QtGui.QMenu(self.menuCreepy)
        self.menuExport_as.setObjectName(_fromUtf8("menuExport_as"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        CreepyMainWindow.setMenuBar(self.menubar)
        self.dockWidget_2 = QtGui.QDockWidget(CreepyMainWindow)
        self.dockWidget_2.setMinimumSize(QtCore.QSize(150, 300))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.dockWidget_2.setFont(font)
        self.dockWidget_2.setObjectName(_fromUtf8("dockWidget_2"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.treeView = QtGui.QTreeView(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.horizontalLayout_3.addWidget(self.treeView)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        CreepyMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)
        self.dockWidget_4 = QtGui.QDockWidget(CreepyMainWindow)
        self.dockWidget_4.setMinimumSize(QtCore.QSize(274, 235))
        self.dockWidget_4.setObjectName(_fromUtf8("dockWidget_4"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.dockWidgetContents_4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.listWidget = QtGui.QListWidget(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.horizontalLayout_4.addWidget(self.listWidget)
        self.dockWidget_4.setWidget(self.dockWidgetContents_4)
        CreepyMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_4)
        self.dockWidget_5 = QtGui.QDockWidget(CreepyMainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_5.sizePolicy().hasHeightForWidth())
        self.dockWidget_5.setSizePolicy(sizePolicy)
        self.dockWidget_5.setObjectName(_fromUtf8("dockWidget_5"))
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName(_fromUtf8("dockWidgetContents_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.dockWidgetContents_5)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.dockWidget_5.setWidget(self.dockWidgetContents_5)
        CreepyMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_5)
        self.dockWidget = QtGui.QDockWidget(CreepyMainWindow)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.dockWidget.setWidget(self.dockWidgetContents)
        CreepyMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.statusbar = QtGui.QStatusBar(CreepyMainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        CreepyMainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(CreepyMainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionExport_as_kml = QtGui.QAction(CreepyMainWindow)
        self.actionExport_as_kml.setCheckable(True)
        self.actionExport_as_kml.setObjectName(_fromUtf8("actionExport_as_kml"))
        self.actionExport_as_csv = QtGui.QAction(CreepyMainWindow)
        self.actionExport_as_csv.setObjectName(_fromUtf8("actionExport_as_csv"))
        self.actionExit = QtGui.QAction(CreepyMainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionReport_a_problem_bug = QtGui.QAction(CreepyMainWindow)
        self.actionReport_a_problem_bug.setObjectName(_fromUtf8("actionReport_a_problem_bug"))
        self.actionAbout = QtGui.QAction(CreepyMainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionSettings = QtGui.QAction(CreepyMainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionLocations_List = QtGui.QAction(CreepyMainWindow)
        self.actionLocations_List.setCheckable(True)
        self.actionLocations_List.setChecked(True)
        self.actionLocations_List.setObjectName(_fromUtf8("actionLocations_List"))
        self.actionResult_Details = QtGui.QAction(CreepyMainWindow)
        self.actionResult_Details.setCheckable(True)
        self.actionResult_Details.setChecked(True)
        self.actionResult_Details.setObjectName(_fromUtf8("actionResult_Details"))
        self.actionAvailable_Plugins = QtGui.QAction(CreepyMainWindow)
        self.actionAvailable_Plugins.setCheckable(True)
        self.actionAvailable_Plugins.setChecked(True)
        self.actionAvailable_Plugins.setObjectName(_fromUtf8("actionAvailable_Plugins"))
        self.actionCurrent_Target_Details = QtGui.QAction(CreepyMainWindow)
        self.actionCurrent_Target_Details.setCheckable(True)
        self.actionCurrent_Target_Details.setObjectName(_fromUtf8("actionCurrent_Target_Details"))
        self.actionToolbars = QtGui.QAction(CreepyMainWindow)
        self.actionToolbars.setObjectName(_fromUtf8("actionToolbars"))
        self.menuExport_as.addAction(self.actionExport_as_kml)
        self.menuExport_as.addAction(self.actionExport_as_csv)
        self.menuCreepy.addAction(self.actionOpen)
        self.menuCreepy.addAction(self.menuExport_as.menuAction())
        self.menuCreepy.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionSettings)
        self.menuAbout.addAction(self.actionReport_a_problem_bug)
        self.menuAbout.addAction(self.actionAbout)
        self.menuView.addAction(self.actionLocations_List)
        self.menuView.addAction(self.actionResult_Details)
        self.menuView.addAction(self.actionAvailable_Plugins)
        self.menuView.addAction(self.actionCurrent_Target_Details)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionToolbars)
        self.menubar.addAction(self.menuCreepy.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(CreepyMainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("activated()")), CreepyMainWindow.close)
        QtCore.QObject.connect(self.actionLocations_List, QtCore.SIGNAL(_fromUtf8("activated()")), self.dockWidget_2.hide)
        QtCore.QMetaObject.connectSlotsByName(CreepyMainWindow)

    def retranslateUi(self, CreepyMainWindow):
        CreepyMainWindow.setWindowTitle(QtGui.QApplication.translate("CreepyMainWindow", "Greepy Geolocation Aggregator", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCreepy.setTitle(QtGui.QApplication.translate("CreepyMainWindow", "Creepy", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExport_as.setTitle(QtGui.QApplication.translate("CreepyMainWindow", "Export as ...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("CreepyMainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("CreepyMainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("CreepyMainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_2.setWindowTitle(QtGui.QApplication.translate("CreepyMainWindow", "Locations List", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_4.setWindowTitle(QtGui.QApplication.translate("CreepyMainWindow", "Available Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_5.setWindowTitle(QtGui.QApplication.translate("CreepyMainWindow", "Current Target Details", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("CreepyMainWindow", "Result Details", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("CreepyMainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_as_kml.setText(QtGui.QApplication.translate("CreepyMainWindow", "Export as kml", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_as_csv.setText(QtGui.QApplication.translate("CreepyMainWindow", "Export as csv", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("CreepyMainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReport_a_problem_bug.setText(QtGui.QApplication.translate("CreepyMainWindow", "Report a problem / bug", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("CreepyMainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("CreepyMainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLocations_List.setText(QtGui.QApplication.translate("CreepyMainWindow", "Locations List", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResult_Details.setText(QtGui.QApplication.translate("CreepyMainWindow", "Result Details", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAvailable_Plugins.setText(QtGui.QApplication.translate("CreepyMainWindow", "Available Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCurrent_Target_Details.setText(QtGui.QApplication.translate("CreepyMainWindow", "Current Target Details", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToolbars.setText(QtGui.QApplication.translate("CreepyMainWindow", "Toolbars", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
